import React from 'react';
import {createPortal} from 'react-dom';
export type Collection={id:string,title:string,line:string,slides:[string,string][],sources:[string,string][],note:string};
export const collections:Collection[]=[
{id:'time',title:'Who decided what time it is?',line:'From local solar time to a shared global reference.',slides:[
 ['Who decided what time it is?','The Sun gives us days. A shared clock is something people had to agree on.'],
 ['Before one time, many local times','Local solar time follows the Sun at each place. Places farther east reach solar noon before places farther west.'],
 ['Faster travel needed a shared clock','Railways and telegraphs made local clock differences a practical problem. A shared reference helped people coordinate.'],
 ['Greenwich became a reference, not a world government','The 1884 conference selected Greenwich as the prime meridian. Countries still decided how to adopt standard time.'],
 ["India’s clock did not change overnight",'A 1905 railway and telegraph circular introduced GMT+5:30. Today, IST is UTC+5:30 and is maintained by CSIR-NPL. The circular is not proof that every local clock changed at once.'],
 ['One reference, many local clocks','UTC combines atomic-clock data from time laboratories. Local time is expressed as an offset from that reference.']
],sources:[['Science Museum: railways and telegraph','https://www.sciencemuseum.org.uk/objects-and-stories/standardising-time-railways-and-electric-telegraph'],['Royal Museums Greenwich: GMT','https://www.rmg.co.uk/stories/time/greenwich-mean-time-gmt'],['Indian Institute of Astrophysics: 1905 circular','https://archives.iiap.res.in/index.php/i22-17'],['CSIR-NPL: Indian Standard Time','https://www.nplindia.org/index.php/science-technology/indian-standard-time-metrology-division/'],['NIST: world time scales','https://www.nist.gov/pml/time-and-frequency-division/popular-links/walk-through-time/walk-through-time-world-time-scales'],['BIPM: UTC','https://www.bipm.org/en/time-department/utc']],note:'The artwork is conceptual illustration, not archival evidence. The 1905 date refers to the railway and telegraph circular, not one universal date for every Indian clock.'},
{"id": "indigo", "title": "How does a green leaf become blue?", "line": "Botany, chemistry and the economy behind a colour.", "slides": [["How does a green leaf become blue?", "Indigo is a colour made through chemistry, work and trade."], ["The blue is not waiting in the flower", "Indigo-bearing leaves contain chemical precursors. Processing turns them into blue pigment."], ["The vat changes what the dye can do", "Indigo pigment does not dissolve in water. Reduction makes a dye bath possible. Exposure to air brings the blue back."], ["A beautiful colour carried a violent economy", "Colonial indigo production in Bengal used an exploitative cultivation system. In 1859-60, growers resisted it."], ["Chemistry changed the supply", "BASF launched synthetic indigo in 1897. Factory production challenged the plant-based industry. Natural-dye practices did not simply disappear."], ["Blue is still a practice, not only a pigment", "Dipping, folding and resist techniques create different patterns and depths of colour. The cloth carries the choices of its makers."]], "sources": [["Taft Museum: dye process", "https://www.taftmuseum.org/more-to-discover/indigo-the-ancient-color-in-your-closet/"], ["Mingei Museum: Blue Gold", "https://mingei.org/exhibitions/blue-gold"], ["Britannica: Indigo Revolt", "https://www.britannica.com/event/Indigo-Revolt"], ["BASF: synthetic launch, 1897", "https://www.basf.com/global/en/who-we-are/history/chronology/1865-1901/1897"], ["Science History Institute: dye archive", "https://digital.sciencehistory.org/works/pn89d780h"], ["Max Planck: natural and synthetic", "https://www.mpiwg-berlin.mpg.de/feature-story/natural-synthetic-rethinking-narratives-chemical-replacement-nineteenth-and-twentieth"]], "note": "Original conceptual illustrations, not historical photographs. The essay treats natural and synthetic indigo as a changing history, not a simple replacement story."},
{"id": "cold", "title": "A cold drink is a small infrastructure story", "line": "Heat, ice cargo and the systems behind the last cold sip.", "slides": [["A cold drink is a small infrastructure story", "Behind a cool glass sit ideas about heat, storage and transport."], ["Cooling existed before the plug", "Water evaporating from a porous clay pot carries heat away. It works best in dry, well-ventilated conditions."], ["Ice was once a cargo", "In the nineteenth century, harvested lake ice crossed oceans. Shipments reached Calcutta. Insulation slowed the melting."], ["A fridge moves heat; it does not create cold", "A refrigeration system takes heat from a cooler space and releases it outside. Energy does the work."], ["Cold has a climate cost", "Cooling needs energy, and refrigerant leaks can add greenhouse gases. Efficient equipment and lower-impact refrigerants matter."], ["Cold is a chain, not a single machine", "Storage and transport have to keep working together. The last cold sip depends on the steps before it."]], "sources": [["Smithsonian: ice to electric refrigeration", "https://americanhistory.si.edu/explore/stories/keeping-your-food-cool-ice-harvesting-electric-refrigeration"], ["Royal Museums Greenwich: ice trade", "https://www.rmg.co.uk/stories/maritime-history/library-archive/ice-trade-cold-business"], ["Hagley: ice harvesting", "https://www.hagley.org/librarynews/patent%3Dmodel-ice-harvesting"], ["MIT D-Lab: clay pot coolers", "https://d-lab.mit.edu/research/evaporative-cooling-vegetable-preservation/clay-pot-coolers"], ["V&A: Mitticool", "https://collections.vam.ac.uk/item/O1331548/mitticool-clay-refrigerator-refrigerator-prajapati-mansukhbhai/"], ["OpenStax: refrigerators and heat pumps", "https://openstax.org/books/university-physics-volume-2/pages/4-3-refrigerators-and-heat-pumps"], ["UNEP/FAO: sustainable cold chains", "https://www.unep.org/resources/report/sustainable-food-cold-chains-opportunities-challenges-and-way-forward"]], "note": "Conceptual illustrations, not archival photographs or engineering diagrams. Clay-pot cooling depends on conditions and is not a guarantee of food safety."},
{"id": "maps", "title": "A map is a choice, not the whole world", "line": "Projection, purpose and the decisions inside a map.", "slides": [["A map is a choice, not the whole world", "Every map selects what to show, what to simplify and what to leave out."], ["A flat world always changes something", "Turning a globe into a flat map introduces distortion. Shape, area, distance and direction cannot all stay faithful everywhere."], ["There is no best projection for everything", "A projection that helps one task can distort another. The useful map depends on the question."], ["The labels tell another story", "Names, boundaries and symbols reflect decisions. Ask who made the map and whose view it carries."], ["Scale decides what survives", "At a smaller scale, features must be simplified or left out. A map of a whole region cannot carry every local detail."], ["Read the map; then read its choices", "Check purpose, scale, date, legend and source. A map is a tool for a question, not a substitute for the world."]], "sources": [["USGS: different projections", "https://www.usgs.gov/faqs/how-are-different-map-projections-used"], ["USGS: map projections", "https://www.usgs.gov/publications/map-projections"], ["UCGIS: cartography and power", "https://gistbok-ltb.ucgis.org/current/concept/CV-01-026"], ["MIT: tale of three maps", "https://mit-serc.pubpub.org/pub/tale-of-three-maps/release/1"], ["Library of Congress: maps collection", "https://www.loc.gov/classroom-materials/maps-from-the-world-digital-library/"], ["British Library: secret maps", "https://www.bl.uk/about/press/releases/british-library-opens-major-exhibition-on-secret-maps"]], "note": "Original conceptual terrain and grid illustrations, not maps for navigation or diagrams of particular projections. No political boundaries are asserted."},
];

const image=(id:string,i:number,thumb=false)=>{const order=thumb?[2,3,5,7,9,11]:[1,4,6,8,10,12];return id==='time'?`/${order[i]}-time-${String(i+1).padStart(2,'0')}${thumb?'-thumb':''}.webp`:`/${({cold:4,indigo:16,maps:28} as Record<string,number>)[id]+i*2+(thumb?0:1)}-${id}-${String(i+1).padStart(2,'0')}${thumb?'-thumb':''}.webp`};
export function Exhibition(){const[open,setOpen]=React.useState<Collection|null>(null);return <section className="t t-exhibition" id="exhibition"><p className="kicker">EXHIBITION / VISUAL ESSAYS</p><h2 className="th">Ideas worth <em>looking into</em></h2><p className="note">Original illustrated essays, with research beside the images. Read at your own pace.</p><div className="ex-collections">{collections.map((c,n)=><button className="ex-collection" key={c.id} onClick={()=>setOpen(c)}><img src={image(c.id,0,true)} alt={c.title} loading="lazy" width="320" height="400"/><span><small>{String(n+1).padStart(2,'0')} / {c.id.toUpperCase()} · {c.slides.length} SLIDES</small><strong>{c.title}</strong><span>{c.line}</span><b>Open essay ↗</b></span></button>)}</div>{open&&<Reader collection={open} close={()=>setOpen(null)}/>}</section>}
function Reader({close,collection}:{close:()=>void,collection:Collection}){
 const {id,title,slides,sources,note}=collection;const total=slides.length;
 const[i,setI]=React.useState(0),[overview,setOverview]=React.useState(false),[notes,setNotes]=React.useState(false);
 const[frame,setFrame]=React.useState({x:0,y:0,w:0,h:0});const stage=React.useRef<HTMLElement>(null);
 const measure=React.useCallback(()=>{const el=stage.current,img=el?.querySelector("img");if(!el||!img?.naturalWidth)return;const scale=Math.min(el.clientWidth/img.naturalWidth,el.clientHeight/img.naturalHeight);const w=img.naturalWidth*scale,h=img.naturalHeight*scale;setFrame({x:(el.clientWidth-w)/2,y:(el.clientHeight-h)/2,w,h})},[]);
 React.useEffect(()=>{if(!stage.current)return;const ro=new ResizeObserver(measure);ro.observe(stage.current);measure();return()=>ro.disconnect()},[overview,i,measure]);
 const ref=React.useRef<HTMLDivElement>(null),start=React.useRef(0),swipedAt=React.useRef(0);
 React.useEffect(()=>{const prev=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();return()=>{document.body.style.overflow=old;prev?.focus()}},[]);
 React.useEffect(()=>{const k=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='ArrowRight')setI(v=>Math.min(total-1,v+1));if(e.key==='ArrowLeft')setI(v=>Math.max(0,v-1));};window.addEventListener('keydown',k);return()=>window.removeEventListener('keydown',k)},[]);
 React.useEffect(()=>{const next=new Image();if(i<total-1)next.src=image(id,i+1)},[i]);
 const key=(e:React.KeyboardEvent)=>{if(e.key==='Tab'){const all=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]');if(all?.length){const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}};
 return createPortal(<div className="ex-reader" role="dialog" aria-modal="true" aria-label={title} ref={ref} tabIndex={-1} onKeyDown={key}><header><span>{id.toUpperCase()} / {i+1} OF {total}</span><div><button onClick={()=>setOverview(!overview)} aria-expanded={overview}>Overview</button><button onClick={()=>setNotes(!notes)} aria-expanded={notes}>Sources & notes</button><button onClick={close} aria-label="Close exhibition">Close ×</button></div></header>{overview?<div className="ex-overview">{slides.map(([t],n)=><button key={t} onClick={()=>{setI(n);setOverview(false)}}><img src={image(id,n,true)} alt="" loading="lazy"/><span>{n+1}. {t}</span></button>)}</div>:<figure ref={stage} className="ex-stage" onTouchStart={e=>start.current=e.changedTouches[0].clientX} onTouchEnd={e=>{const d=e.changedTouches[0].clientX-start.current;if(Math.abs(d)>50){swipedAt.current=Date.now();setI(v=>Math.max(0,Math.min(total-1,v+(d<0?1:-1))))}}}><img onLoad={measure} key={i} src={image(id,i)} alt={slides[i][0]+'. '+slides[i][1]}/><button className="ex-zone ex-zone-prev" style={{left:frame.x,top:frame.y,width:frame.w*.4,height:frame.h,bottom:"auto"}} aria-label="Previous slide by tapping left side" disabled={i===0} onClick={()=>{if(Date.now()-swipedAt.current>400)setI(v=>Math.max(0,v-1))}}/><button className="ex-zone ex-zone-next" style={{left:frame.x+frame.w*.4,top:frame.y,width:frame.w*.6,height:frame.h,bottom:"auto",right:"auto"}} aria-label="Next slide by tapping right side" disabled={i===total-1} onClick={()=>{if(Date.now()-swipedAt.current>400)setI(v=>Math.min(total-1,v+1))}}/></figure>}<footer><button disabled={i===0} onClick={()=>{setI(i-1);setOverview(false)}} aria-label="Previous slide">← Previous</button><div><p>{slides[i][0]}</p><span>{String(i+1).padStart(2,'0')} / {String(total).padStart(2,'0')}</span></div><button disabled={i===total-1} onClick={()=>{setI(i+1);setOverview(false)}} aria-label="Next slide">Next →</button></footer>{notes&&<aside className="ex-notes"><button onClick={()=>setNotes(false)}>Close notes ×</button><h3>Research beside the images</h3><p>{slides[i][1]}</p><p>{note}</p><ul>{sources.map(([t,u])=><li key={u}><a href={u} target="_blank" rel="noreferrer">{t} ↗</a></li>)}</ul></aside>}</div>,document.body)
}
