import React from 'react';
import {createPortal} from 'react-dom';
const title='Who decided what time it is?';
const slides=[
 ['Who decided what time it is?','The Sun gives us days. A shared clock is something people had to agree on.'],
 ['Before one time, many local times','Local solar time follows the Sun at each place. Places farther east reach solar noon before places farther west.'],
 ['Faster travel needed a shared clock','Railways and telegraphs made local clock differences a practical problem. A shared reference helped people coordinate.'],
 ['Greenwich became a reference, not a world government','The 1884 conference selected Greenwich as the prime meridian. Countries still decided how to adopt standard time.'],
 ["India’s clock did not change overnight",'A 1905 railway and telegraph circular introduced GMT+5:30. Today, IST is UTC+5:30 and is maintained by CSIR-NPL. The circular is not proof that every local clock changed at once.'],
 ['One reference, many local clocks','UTC combines atomic-clock data from time laboratories. Local time is expressed as an offset from that reference.']
];
const sources=[['Science Museum: railways and telegraph','https://www.sciencemuseum.org.uk/objects-and-stories/standardising-time-railways-and-electric-telegraph'],['Royal Museums Greenwich: GMT','https://www.rmg.co.uk/stories/time/greenwich-mean-time-gmt'],['Indian Institute of Astrophysics: 1905 circular','https://archives.iiap.res.in/index.php/i22-17'],['CSIR-NPL: Indian Standard Time','https://www.nplindia.org/index.php/science-technology/indian-standard-time-metrology-division/'],['NIST: world time scales','https://www.nist.gov/pml/time-and-frequency-division/popular-links/walk-through-time/walk-through-time-world-time-scales'],['BIPM: UTC','https://www.bipm.org/en/time-department/utc']];
const image=(i:number,thumb=false)=>{const order=thumb?[2,3,5,7,9,11]:[1,4,6,8,10,12];return `/${order[i]}-time-${String(i+1).padStart(2,'0')}${thumb?'-thumb':''}.webp`};
export function Exhibition(){
 const[open,setOpen]=React.useState(false);
 return <section className="t t-exhibition" id="exhibition"><p className="kicker">EXHIBITION / VISUAL ESSAYS</p><h2 className="th">Ideas worth <em>looking into</em></h2><p className="note">Original illustrated essays, with research beside the images. Read at your own pace.</p><button className="ex-collection" onClick={()=>setOpen(true)}><img src={image(0,true)} alt="Illustrated clock and railway poster" loading="lazy" width="320" height="400"/><span><small>01 / TIME · 6 SLIDES</small><strong>{title}</strong><span>From local solar time to a shared global reference.</span><b>Open essay ↗</b></span></button>{open&&<Reader close={()=>setOpen(false)}/>}</section>
}
function Reader({close}:{close:()=>void}){
 const[i,setI]=React.useState(0),[overview,setOverview]=React.useState(false),[notes,setNotes]=React.useState(false);
 const ref=React.useRef<HTMLDivElement>(null),start=React.useRef(0);
 React.useEffect(()=>{const prev=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();return()=>{document.body.style.overflow=old;prev?.focus()}},[]);
 React.useEffect(()=>{const k=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='ArrowRight')setI(v=>Math.min(5,v+1));if(e.key==='ArrowLeft')setI(v=>Math.max(0,v-1));};window.addEventListener('keydown',k);return()=>window.removeEventListener('keydown',k)},[]);
 React.useEffect(()=>{const next=new Image();if(i<5)next.src=image(i+1)},[i]);
 const key=(e:React.KeyboardEvent)=>{if(e.key==='Tab'){const all=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]');if(all?.length){const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}};
 return createPortal(<div className="ex-reader" role="dialog" aria-modal="true" aria-label={title} ref={ref} tabIndex={-1} onKeyDown={key}><header><span>TIME / {i+1} OF 6</span><div><button onClick={()=>setOverview(!overview)} aria-expanded={overview}>Overview</button><button onClick={()=>setNotes(!notes)} aria-expanded={notes}>Sources & notes</button><button onClick={close} aria-label="Close exhibition">Close ×</button></div></header>{overview?<div className="ex-overview">{slides.map(([t],n)=><button key={t} onClick={()=>{setI(n);setOverview(false)}}><img src={image(n,true)} alt="" loading="lazy"/><span>{n+1}. {t}</span></button>)}</div>:<figure className="ex-stage" onTouchStart={e=>start.current=e.changedTouches[0].clientX} onTouchEnd={e=>{const d=e.changedTouches[0].clientX-start.current;if(Math.abs(d)>50)setI(v=>Math.max(0,Math.min(5,v+(d<0?1:-1))))}}><img key={i} src={image(i)} alt={slides[i][0]+'. '+slides[i][1]}/></figure>}<footer><button disabled={i===0} onClick={()=>{setI(i-1);setOverview(false)}} aria-label="Previous slide">← Previous</button><div><p>{slides[i][0]}</p><span>{String(i+1).padStart(2,'0')} / 06</span></div><button disabled={i===5} onClick={()=>{setI(i+1);setOverview(false)}} aria-label="Next slide">Next →</button></footer>{notes&&<aside className="ex-notes"><button onClick={()=>setNotes(false)}>Close notes ×</button><h3>Research beside the images</h3><p>{slides[i][1]}</p><p>The artwork is conceptual illustration, not archival evidence. The 1905 date refers to the railway and telegraph circular, not one universal date for every Indian clock.</p><ul>{sources.map(([t,u])=><li key={u}><a href={u} target="_blank" rel="noreferrer">{t} ↗</a></li>)}</ul></aside>}</div>,document.body)
}
