import React from 'react';
import { projects } from './projects';
import { profile } from './data';

const rawMedia = projects.flatMap(p => {
  const images = [...new Set([p.cover, ...p.panels.map(x => x.image)].filter(Boolean))] as string[];
  const rows = images.map((src,i) => ({src, title:p.title, subtitle:i ? p.panels.find(x=>x.image===src)?.caption : p.summary, link:p.link, issue:p.readerIssue, video:''}));
  if(p.film) rows.unshift({src:p.film.poster || '',title:p.title,subtitle:'40-second cinematic concept · Play with sound controls',link:p.link,issue:undefined,video:p.film.src || ''});
  return rows;
});
const leads = projects.map(p=>rawMedia.find(m=>m.title===p.title)).filter(Boolean) as typeof rawMedia;
const media = [...leads,...rawMedia.filter(m=>!leads.includes(m))];
for(let i=1;i<=10;i++){ const src=`/covers/issue-${String(i).padStart(2,'0')}.jpg`;if(!media.some(x=>x.src===src))media.push({src,title:`Cover Stories · Issue ${String(i).padStart(2,'0')}`,subtitle:'Fictional editorial cover',link:undefined,issue:i,video:''});}
export function FeaturedMedia(){
 const [paused,setPaused]=React.useState(false);const windowRef=React.useRef<HTMLDivElement>(null);const move=(direction:number)=>{setPaused(true);windowRef.current?.scrollBy({left:direction*(innerWidth<760?308:398),behavior:"smooth"});};const [playing,setPlaying]=React.useState(false);
 return <section className="featured-media" aria-label="Featured media gallery"><div className="film-heading"><p className="kicker"><b>FEATURED MEDIA</b> / FILMS · IMAGES · EXPERIMENTS</p><button className="pill" onClick={()=>setPaused(!paused)}>{paused?'Resume motion':'Pause motion'}</button></div><div className="gallery-controls"><button className="pill" aria-label="Previous media" onClick={()=>move(-1)}>←</button><button className="pill" aria-label="Next media" onClick={()=>move(1)}>→</button></div><div className="media-window" ref={windowRef}><div className={`media-track ${paused||playing?'paused':''}`}>
 {[0,1].map(copy=><div className="media-set" key={copy} aria-hidden={copy===1?true:undefined}>{media.map((m,i)=><article className="media-card" key={`${copy}-${i}`}>{m.video?<video src={m.video} poster={m.src} controls playsInline preload="none" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} tabIndex={copy?-1:0}/>:<img src={m.src} alt={m.title} loading="lazy"/>}<div><small>{m.video?'FILM':'VISUAL'}</small><h3>{m.title}</h3><p>{m.subtitle}</p>{m.link?<a tabIndex={copy?-1:0} href={m.link}>Open project ↗</a>:<button tabIndex={copy?-1:0} onClick={()=>{document.getElementById(m.issue?'covers':'work')?.scrollIntoView({behavior:'smooth'});if(m.issue)window.dispatchEvent(new CustomEvent('open-cover-stories',{detail:m.issue}));}}>Explore work ↗</button>}</div></article>)}</div>)}
 </div></div><p className="gallery-note">Best work first. Hover, focus or use Pause to stop motion. Every project is available below.</p></section>
}
export function About(){return <section className="t t-about" id="about"><p className="kicker">01 / ABOUT</p><h2 className="th">Anurag Dutta.<br/><em>AI creative.</em></h2><p className="about-copy">I specialize in AI creative work: images, films, social content and digital experiences. I'm preparing for a job in this field, building a portfolio that shows the work as well as the thinking behind it.</p><p className="note">Open to AI creative roles. The brand projects here are concepts, not launched products or client results.</p><a className="btn btn-ghost" href={`mailto:${profile.email}`}>Start a conversation ↗</a></section>}
export function Evidence(){return <section className="t t-evidence" id="case-studies"><p className="kicker">02 / THINKING BEHIND THE WORK</p><h2 className="th">Choices, not <em>just outputs.</em></h2><div className="evidence-grid"><article><span>01 / TOLA</span><h3>A gap worth questioning.</h3><p>The first idea, "ergonomic and light", was already taken. The case study pivots to a printed load label and separates sourced evidence from untested assumptions.</p><p className="note">Not yet known: parent willingness to pay, school participation and manufacturing cost.</p><a href="/brands/tola/case-study.html">Read the case study ↗</a></article><article><span>02 / SOOKHA</span><h3>A concept with its limits intact.</h3><p>A rain jacket for the commute, with the research, product choices and open questions shown alongside the brand and campaign.</p><p className="note">Concept project. No manufactured jacket, certified performance or sales results.</p><a href="/brands/sookha/case-study.html">Read the case study ↗</a></article><article><span>03 / BELOW THE SURFACE</span><h3>Explain first. Then illustrate.</h3><p>A five-frame story starts with one question: why does a well need stairs? It connects changing water levels, climate and gathering spaces with a source list.</p><p className="note">AI illustrations, not documentary photographs. Swipe the frames and inspect the sources.</p><a href="/social/stepwells/">Read the visual story ↗</a></article></div></section>}
